services:

  mongodb:
    image: mongo:7.0.16-jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  ssp:
    image: ssp
    build: .
    restart: always
    depends_on:
      - redis
      - mongodb
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      REDIS_URL: ${REDIS_URL}
      MONGODB_URI: ${MONGODB_URI}
      TESTING_MONGODB_URI: ${TESTING_MONGODB_URI}
      DEEPL_API_KEY: ${DEEPL_API_KEY}

volumes:
  mongo_data:
